const { Resend } = require("resend");
const logger = require("../config/logger");

const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * Convert markdown-style summary to clean HTML email
 */
const markdownToHtml = (text) => {
  return text
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(
      /^## (.+)$/gm,
      '<h2 style="color:#1a1a2e;margin-top:24px;margin-bottom:8px;font-size:18px;border-bottom:2px solid #e63946;padding-bottom:4px;">$1</h2>'
    )
    .replace(
      /^### (.+)$/gm,
      '<h3 style="color:#457b9d;margin-top:16px;font-size:15px;">$1</h3>'
    )
    .replace(/^- (.+)$/gm, '<li style="margin:6px 0;color:#333;">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, (match) => `<ul style="padding-left:20px;margin:8px 0;">${match}</ul>`)
    .replace(/\n\n/g, '</p><p style="margin:10px 0;line-height:1.7;color:#444;">')
    .replace(/\n/g, "<br>");
};

/**
 * Send the generated sales summary using Resend
 */
const sendSummaryEmail = async (recipientEmail, summary, filename, requestId) => {
  const fromName = process.env.EMAIL_FROM_NAME || "Rabbitt AI Sales Insights";
  const fromAddress = process.env.EMAIL_FROM_ADDRESS || "onboarding@resend.dev";

  const htmlSummary = markdownToHtml(summary);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const htmlBody = `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f4f8;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f8;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="620" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

          <tr>
            <td style="background:#1a1a2e;padding:36px 40px;color:white;">
              <p style="margin:0;color:#e63946;font-size:12px;font-weight:700;">Rabbitt AI</p>
              <h1 style="margin:8px 0 0;font-size:26px;">Sales Insight Report</h1>
              <p style="margin:6px 0 0;color:#a8b2c8;">${dateStr} · Source: <em>${filename}</em></p>
            </td>
          </tr>

          <tr>
            <td style="padding:36px 40px;">
              ${htmlSummary}
            </td>
          </tr>

          <tr>
            <td style="background:#f8f9fc;border-top:1px solid #eee;padding:20px 40px;">
              <p style="margin:0;color:#999;font-size:12px;">
                Generated by <strong>Rabbitt AI Sales Insight Automator</strong>
              </p>
              <p style="margin:4px 0 0;color:#bbb;font-size:11px;">
                Request ID: ${requestId}
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  const textBody = `
RABBITT AI — SALES INSIGHT REPORT
=================================
Date: ${dateStr}
Source File: ${filename}
Request ID: ${requestId}

${summary}

---
Generated by Rabbitt AI Sales Insight Automator
`;

  logger.info("Sending email via Resend", { to: recipientEmail, filename, requestId });

  try {
    const response = await resend.emails.send({
      from: `${fromName} <${fromAddress}>`,
      to: recipientEmail,
      subject: `📊 Sales Insight Report — ${filename}`,
      html: htmlBody,
      text: textBody,
    });

    logger.info("Email sent successfully", { id: response.data?.id });

    return response.data?.id;
  } catch (err) {
    logger.error("Resend email error", { error: err.message });

    throw new Error(`Email delivery failed: ${err.message}`);
  }
};

module.exports = { sendSummaryEmail };